### ISSUE TITLE
WhisperX :  Suggestion

### ISSUE THREAD

**Issue by AlexisSerneels** [shaishaicookie/fcpx-auto-captions#1]
Thank you for this tool. It’s a great implementation. I’ve done the same, without GUI for Whisper and FCP. 

What I’m facing now is the limitation of Whisper which might not be extremely precise some times. Their developer won’t fix and suggest trying WhisperX (https://github.com/m-bain/whisperX)

It needs Python though and my knowledge is limited in this domain. Maybe that is something you are more confortable with and would know how to implement in your script in order to get word precise level.

**Comment by shaishaicookie** [comment]
Thank you for your suggestion. I will take a look at the WhisperX repository and understand how it improves accuracy. In this project, I chose to use whisper.cpp instead of the native Python version of Whisper by OpenAI because whisper.cpp is 5-45 times faster on computers without NVIDIA GPUs. You can find a speed comparison in this blog post: https://blog.castopod.org/install-whisper-cpp-on-your-mac-in-5mn-and-transcribe-all-your-podcasts-for-free/. I hope this information is helpful to you.
